apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-web
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8080 ## le port sur lequel les containers écoutent
      targetPort: 8080 ## port exposé en interne dans le cluster
      nodePort: 30008 ## Port d'accès (limité 30000-32767 pour nodePort)

